name: gwtc
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiobotocore=2.25.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arviz=0.22.0
  - astroplan=0.10.1
  - astropy-healpix=1.1.2
  - astropy-iers-data=0.2025.12.8.0.38.44
  - asttokens=3.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.2
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - backports.zstd=1.2.0
  - bcrypt=5.0.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - blosc=1.21.6
  - botocore=1.40.70
  - bottleneck=1.6.0
  - bqplot=0.12.45
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.22.0
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.11.12
  - cffi=2.0.0
  - cfitsio=4.6.3
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - chealpix=3.31.0
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - corner=2.2.3
  - cpython=3.11.14
  - cryptography=46.0.3
  - cycler=0.12.1
  - cython=3.2.2
  - cytoolz=1.1.0
  - dask=2025.11.0
  - dask-core=2025.11.0
  - dask-image=2025.11.0
  - dateparser=1.2.2
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - deprecated=1.3.1
  - distributed=2025.11.0
  - donfig=0.8.1.post1
  - dqsegdb2=1.3.0
  - executing=2.2.1
  - fftw=3.3.10
  - fonttools=4.61.0
  - freetype=2.14.1
  - frozenlist=1.7.0
  - fsspec=2025.12.0
  - future=1.0.0
  - gast=0.4.0
  - geos=3.14.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-crc32c=1.8.0
  - gsl=2.7
  - gwdatafind=2.1.1
  - gwosc=0.8.1
  - gwpy=3.0.13
  - h2=4.3.0
  - h5netcdf=1.7.3
  - h5py=3.15.1
  - hdf5=1.14.6
  - healpy=1.19.0
  - hpack=4.1.0
  - htcondor-classads=24.12.4
  - htgettoken=2.5
  - html5lib=1.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - igwn-auth-utils=1.4.0
  - igwn-ligolw=2.1.0
  - igwn-segments=2.1.0
  - imagecodecs=2025.11.11
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - invoke=2.2.1
  - ipydatagrid=1.4.0
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.2
  - jplephem=2.23
  - jq=1.8.1
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - jxrlib=1.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lalinference-data=4.1.9
  - lalsimulation-data=6.2.0
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - ldas-tools-al=2.7.0
  - ldas-tools-framecpp=2.9.3
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libboost=1.88.0
  - libboost-python=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcondor_utils=24.12.4
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libframel=8.48.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblal=7.7.0
  - liblalburst=2.0.7
  - liblalframe=3.0.7
  - liblalinference=4.1.9
  - liblalinspiral=5.0.3
  - liblalmetaio=4.0.6
  - liblalsimulation=6.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmetaio=8.5.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.2
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - ligo-gracedb=2.14.3
  - ligo-segments=1.4.0
  - ligo.em-bright=1.2.1
  - ligo.skymap=2.4.0
  - ligotimegps=2.1.0
  - locket=1.0.0
  - lscsoft-glue=4.1.1
  - lz4=4.4.5
  - lz4-c=1.10.0
  - mako=1.3.10
  - markupsafe=3.0.3
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.2.1
  - minio=7.2.20
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpld3=0.5.12
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - multidict=6.6.3
  - munge=0.5.16
  - munkres=1.1.4
  - narwhals=2.13.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - numcodecs=0.16.5
  - numpy=1.26.4
  - oniguruma=6.9.10
  - openjpeg=2.5.4
  - openssl=3.6.0
  - orc=2.2.1
  - packaging=25.0
  - pandas=2.3.3
  - paramiko=4.0.0
  - parso=0.8.5
  - partd=1.4.2
  - pcre2=10.46
  - pegasus-wms.api=5.0.9
  - pegasus-wms.common=5.0.9
  - pesummary=1.5.6
  - pexpect=4.9.0
  - pillow=12.0.0
  - pims=0.7
  - pip=25.3
  - pkg-config=0.29.2
  - platformdirs=4.5.1
  - plotly=6.5.0
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.1.3
  - ptemcee=1.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py2vega=0.6.1
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pyavm=0.9.8
  - pycbc=2.10.0
  - pycparser=2.22
  - pycryptodome=3.23.0
  - pyerfa=2.0.1.5
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pykerr=0.2.0
  - pynacl=1.6.1
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-gssapi=1.10.1
  - python-htcondor=24.12.4
  - python-lal=7.7.0
  - python-lalburst=2.0.7
  - python-lalframe=3.0.7
  - python-lalinference=4.1.9
  - python-lalinspiral=5.0.3
  - python-lalmetaio=4.0.6
  - python-lalsimulation=6.2.0
  - python-ligo-lw=1.8.3
  - python-tzdata=2025.2
  - python_abi=3.11
  - pyseobnr=0.3.5
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - rav1e=0.7.1
  - re2=2025.11.05
  - readline=8.2
  - regex=2025.11.3
  - reproject=0.19.0
  - requests=2.32.5
  - s2n=1.6.2
  - s3fs=2025.12.0
  - safe-netrc=1.0.1
  - scikit-learn=1.2.1
  - scipy=1.16.3
  - scitokens=1.8.1
  - scitokens-cpp=1.2.0
  - setuptools=80.9.0
  - shapely=2.1.2
  - six=1.17.0
  - slicerator=1.1.0
  - snappy=1.2.2
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tblib=3.2.2
  - threadpoolctl=3.6.0
  - tifffile=2025.12.12
  - tk=8.6.13
  - toolz=1.1.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - uncompresspy=0.4.1
  - unicodedata2=17.0.0
  - urllib3=2.6.1
  - wcwidth=0.2.14
  - webencodings=0.5.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wrapt=1.17.3
  - xarray=2025.12.0
  - xarray-einstats=0.9.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - yarl=1.22.0
  - zarr=3.1.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - allure-python-commons==2.15.3
      - annotated-types==0.7.0
      - argcomplete==3.6.3
      - astropy==6.1.4
      - astroquery==0.4.11
      - backports-tarfile==1.2.0
      - bioblend==1.7.0
      - black==25.12.0
      - bokeh==3.1.1
      - boltons==25.0.0
      - cachecontrol==0.14.4
      - coloredlogs==15.0.1
      - conda-package-streaming==0.12.0
      - ct3==3.4.0.post5
      - cwl-upgrader==1.2.14
      - cwl-utils==0.40
      - cwltool==3.1.20260108082145
      - distlib==0.4.0
      - docutils==0.22.4
      - edam-ontology==1.25.3
      - ephemeris==0.10.11
      - filelock==3.20.3
      - galaxy-job-config-init==0.1.3
      - galaxy-tool-util==25.1.0
      - galaxy-tool-util-models==25.1.0
      - galaxy-util==25.1.0
      - glob2==0.7
      - gxformat2==0.21.0
      - humanfriendly==10.0
      - importlib-resources==6.5.2
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jeepney==0.9.0
      - json-tricks==3.17.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keyring==25.7.0
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - more-itertools==10.8.0
      - mypy-extensions==1.1.0
      - oda-api==1.2.41
      - oyaml==1.0
      - pathspec==0.12.1
      - pathvalidate==3.3.1
      - planemo==0.75.34
      - pluggy==1.6.0
      - prov==1.5.1
      - puremagic==1.30
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydot==4.0.1
      - pysam==0.23.3
      - pytokens==0.3.0
      - pyvo==1.8
      - rdflib==7.5.0
      - referencing==0.37.0
      - repoze-lru==0.7
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rich-argparse==1.7.2
      - routes==2.5.1
      - rpds-py==0.30.0
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - schema-salad==8.9.20251102115403
      - secretstorage==3.5.0
      - spython==0.3.14
      - tabulate==0.9.0
      - tinydb==4.8.2
      - tuspy==1.1.0
      - typing-inspection==0.4.2
      - virtualenv==20.36.1
      - zipstream-new==1.1.8
      - zstandard==0.25.0
prefix: /home/sentenac/miniforge3/envs/igwn
